# Generated by Django 3.0.6 on 2021-03-14 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('powerschool_id', models.CharField(default='', max_length=20)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('grade', models.IntegerField(choices=[(6, 'Grade 6'), (7, 'Grade 7'), (8, 'Grade 8')], default=6)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=6)),
                ('social_grouping', models.CharField(default='', max_length=200)),
                ('arabic', models.CharField(choices=[('N', 'Native'), ('NN', 'Non-Native'), ('None', 'None')], default='NN', max_length=6)),
                ('islamic', models.CharField(choices=[('N', 'Native'), ('NN', 'Non-Native'), ('None', 'None')], default='None', max_length=6)),
                ('takes_native_arabic', models.BooleanField(default=False)),
                ('takes_islamic', models.BooleanField(default=False)),
                ('nationality', models.CharField(default='', max_length=200)),
                ('ell', models.CharField(default='N', max_length=1)),
                ('send', models.CharField(default='N', max_length=1)),
                ('behavior', models.CharField(default='', max_length=200)),
                ('hmp', models.CharField(default='', max_length=200)),
                ('hORl', models.CharField(choices=[('N', 'None'), ('H', 'H'), ('L', 'L')], default='N', max_length=4)),
                ('friend1', models.IntegerField(default=-1, max_length=3)),
                ('friend2', models.IntegerField(default=-1, max_length=3)),
                ('friend3', models.IntegerField(default=-1, max_length=3)),
                ('friend4', models.IntegerField(default=-1, max_length=3)),
                ('friend5', models.IntegerField(default=-1, max_length=3)),
                ('avoid', models.CharField(default='', max_length=200)),
                ('notes', models.CharField(default='', max_length=300)),
            ],
        ),
    ]
