# Generated by Django 3.0.6 on 2021-03-15 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_maker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='previous_grade',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
