# Generated by Django 3.0.6 on 2021-03-19 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_maker', '0002_student_previous_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='friends_unprocessed',
            field=models.CharField(default=34, max_length=300),
            preserve_default=False,
        ),
    ]
